server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9999/eureka}
  instance:
    preferIpAddress: true


spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: rest-server
          uri: lb://rest-server
          predicates:
            - Path=/rest/**
#        - id: book-store
#          uri: lb://book-store
#          predicates:
#            - Path=/book/**
