spring:
  application:
    name: rest-client

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9999/eureka}

feign:
  circuitbreaker:
    enabled: true
